development:
  adapter: postgresql
  encoding: unicode
  database: property_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: property_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: property_production
  pool: 5
  username:
  password:
